//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultItem
    {
        public int Id { get; set; }
        public int VaultId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
    
        public virtual Vault Vault { get; set; }
    }
}
