//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultAcessLog
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string AdressIP { get; set; }
        public string Message { get; set; }
        public string Access { get; set; }
        public Nullable<int> VaultId { get; set; }
    }
}
