//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultUser
    {
        public int VaultId { get; set; }
        public string UserId { get; set; }
        public string AccessLevel { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public int Id { get; set; }
    
        public virtual Vault Vault { get; set; }
    }
}
