//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaultEntities : DbContext
    {
        public VaultEntities()
            : base("name=VaultEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vault> Vault { get; set; }
        public virtual DbSet<VaultAcessLog> VaultAcessLog { get; set; }
        public virtual DbSet<VaultUser> VaultUser { get; set; }
        public virtual DbSet<VaultItem> VaultItem { get; set; }
    }
}
